config/routes.rb
Rails.application.routes.draw do

  root 'products#index'
  
  resources :products do
    member do
      get :delete
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord

    scope :sorted, lambda { order("id ASC")}
    scope :newest_first, lambda { order("created_at DESC")}

end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController


  def index
    @products = Product.sorted
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

  def create
    # Instantiate a new object using form parameters
    @product = Product.new()
    # Save the object
    if @product.save
      # If save succeeds, redirect to the index action
      redirect_to(products_path)
    else
      # If save fails, redisplay the form so user can fix problems
      render('new')
    end
  end

  def edit
  end

  def delete
  end

  private

  def product_params
    params.require(:product).permit(:name, :description, :price, :image, :cpu, :camera, :size, :weight, :display, :battery, :memory)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WebStore</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/delete.html.erb
<h1>Products#delete</h1>
<p>Find me in app/views/products/delete.html.erb</p>

app/views/products/edit.html.erb
<h1>Products#edit</h1>
<p>Find me in app/views/products/edit.html.erb</p>

app/views/products/index.html.erb
<div class="products index">
    <h2>Products</h2>
    <%= link_to("Add new Product", new_product_path, :class => 'action new') %>

    <table class="listing" summary="Product list">
        <tr class='header'>
            <th>#</th>
            <th>Image</th>
            <th>Name</th>
            <th>Description</th>
            <th>Price</th>
           
            <th></th>
        </tr>
        <% @products.each do |product| %>
        <tr>
            <td><%= product.id %></td>
            <td><%= image_tag(product.image) %></td>
            <td><%= product.name %></td>
            <td><%= simple_format(truncate(product.description, :length => 50)) %></td>
            <td><%= product.price %></td>
           
            <td class="actions">
                <%= link_to("Show", product_path(product), :class => 'action show') %>
                <%= link_to("Edit", "#", :class => 'action edit') %>
                <%= link_to("Delete", "#", :class => 'action delete') %>
            <td>
        </tr>
        <% end %>
    </table>

app/views/products/new.html.erb
<h2>Create Product</h2>

<%= form_for(@product,:url => products_path, :method => 'post') do |f| %>
    <table summary="Product form fields">
        <tr>
            <th>Name</th>
            <td><%= f.text_field(:name) %></td>
        </tr>
        <tr>
            <th>Description</th>
            <td><%= f.text_field(:description) %></td>
        </tr>
        <tr>
            <th>Price</th>
            <td><%= f.text_field(:price) %></td>
        </tr>
       
        <tr>
            <th>CPU</th>
            <td><%= f.text_field(:cpu) %></td>
        </tr>
        <tr>
            <th>Camera</th>
            <td><%= f.text_field(:camera) %></td>
        </tr>
        <tr>
            <th>Size</th>
            <td><%= f.text_field(:size) %></td>
        </tr>
        <tr>
            <th>Weight</th>
            <td><%= f.text_field(:weight) %></td>
        </tr>
        <tr>
            <th>Display</th>
            <td><%= f.text_field(:display) %></td>
        </tr>
        <tr>
            <th>Battery</th>
            <td><%= f.text_field(:battery) %></td>
        </tr>
        <tr>
            <th>Memory</th>
            <td><%= f.text_field(:memory) %></td>
        </tr>
    </table>

    <div class="form-buttons">
        <%= f.submit("Create Subject") %>
    </div>
<% end %>

app/views/products/show.html.erb
<%= link_to("<< Back to List", products_path, :class => 'back-link')%>

<div class="products show">
    <h2>Show Product</h2>

    <table summary="Product detail view">
        <tr>
            <th>Name</th>
            <td><%= @product.name %></td>
        </tr>
        <tr>
            <th>Id</th>
            <td><%= @product.id %></td>
        </tr>
        <tr>
            <th>Description</th>
            <td><%= @product.description %></td>
        </tr>
        <tr>
            <th>Price</th>
            <td><%= @product.price %></td>
        </tr>
        <tr>
            <th>CPU</th>
            <td><%= @product.cpu %></td>
        </tr>
        <tr>
            <th>Camera</th>
            <td><%= @product.camera %></td>
        </tr>
        <tr>
            <th>Size</th>
            <td><%= @product.size %></td>
        </tr>
        <tr>
            <th>Weight</th>
            <td><%= @product.weight %></td>
        </tr>
        <tr>
            <th>Display</th>
            <td><%= @product.display %></td>
        </tr>
        <tr>
            <th>Battery</th>
            <td><%= @product.battery %></td>
        </tr>
        <tr>
            <th>Memory</th>
            <td><%= @product.memory %></td>
        </tr>
        <tr>
            <th>Created</th>
            <td><%= @product.created_at%></td>
        </tr>
        <tr>
            <th>Updated</th>
            <td><%= @product.updated_at %></td>
        </tr>
    </table>
</div>